[1/2] STEP 6/7: COPY . .
--> a63da15a9d76
[1/2] STEP 7/7: RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o secret-operator main.go
go: updates to go.mod needed; to update it:
	go mod tidy
Error: building at STEP "RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o secret-operator main.go": while running runtime: exit status 1
